name: CHANGE REQUEST WORKFLOW

on:
  workflow_dispatch: # Manual trigger
    inputs:
      ServiceNow CR:
        required: true
        type: string
        description: 'ServiceNow Change Request Number'

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyyaml snowflake-connector-python gitpython

      - name: Run SQL scripts
        run: python pipeline_scripts/script.py