name: DML_CHANGES_WORKFLOW_NEW

on:
  workflow_dispatch: # Manual trigger
    branches:
      - main
    inputs:
      ServiceNow CR:
        required: true
        type: string
        description: 'ServiceNow Change Request Number'

jobs:
  dml_changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with full history to detect file changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to ensure proper diff detection

      # Find the latest changed SQL file in the DML_CHANGES folder
      - name: Set executable permissions for the script
        run: chmod +x .github/workflows/script/fetch_changed_files_script.sh
      - name: Find latest changed json file in dml_changes
        id: get_sql_file
        run: |
          folder="dml_changes/DEV"
          file_extension=".sql"
          log_count=1

          filtered_files=$(.github/workflows/script/fetch_changed_files_script.sh "$folder" "$file_extension" "$log_count" "$GITHUB_JOB")
          if [ -z "$filtered_files" ]; then
            echo "No sql file changes detected in dml_changes."
            echo "sql_files=[]" >> $GITHUB_ENV
          else
            sql_files=$(echo "$filtered_files" | jq -R -s -c 'split("\n")[:-1]')
            echo "sql file found: $sql_files"
            echo "sql_files=$sql_files" >> $GITHUB_ENV
          fi
      - name: Install python packages
        if: ${{ env.sql_files != '[]' }}
        run: |
          pip install snowflake-connector-python
      - name: Run Python Script
        if: ${{ env.sql_files != '[]' }}
        env:
          SNOWFLAKE_ACCOUNT: YQEWXYI-GY20588
          SNOWFLAKE_USERNAME: MANIDEEPMADHA
          SNOWFLAKE_PASSWORD: Mani@snowflake1432
          SNOWFLAKE_WAREHOUSE: 'COMPUTE_WH'
          ADDED_FILES: ${{ env.sql_files }}
        run: |
          python .github/workflows/script/dml_changes_script.py  
