name: DML_CHANGES_WORKFLOW_NEW

on:
  workflow_dispatch: # Manual trigger
    inputs:
      ServiceNow CR:
        required: true
        type: string
        description: 'ServiceNow Change Request Number'

jobs:
  dml_changes:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with full history to detect file changes
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history to ensure proper diff detection

      # Find the latest changed SQL file in the DML_CHANGES folder
      - name: Find latest changed SQL file in DML_CHANGES
        id: get_sql_file
        run: |
          latest_commit=$(git log -1 --pretty=format:%H)
          changed_files=$(git diff-tree --no-commit-id --name-status -r $latest_commit)
          echo $ changed_files
          # Filter SQL files in the specified folder
          filtered_files=$(echo "$changed_files" | grep "DML_CHANGES/DEV" | grep ".sql" | awk '$1 != "D" {print $NF}' || true)
          if [ -z "$filtered_files" ]; then
            echo "No SQL file changes detected in DML_CHANGES."
            echo "sql_files=[]" >> $GITHUB_ENV
          else
            sql_files=$(echo "$filtered_files" | jq -R -s -c 'split("\n")[:-1]')
            echo "SQL file found: $sql_files"
            echo "sql_files=$sql_files" >> $GITHUB_ENV
          fi
      - name: Install python packages
        if: ${{ env.sql_files != '[]' }}
        run: |
          pip install snowflake-connector-python
      - name: Run Python Script
        if: ${{ env.sql_files != '[]' }}
        env:
          SNOWFLAKE_ACCOUNT: YQEWXYI-GY20588
          SNOWFLAKE_USERNAME: MANIDEEPMADHA
          SNOWFLAKE_PASSWORD: Mani@snowflake1432
          SNOWFLAKE_WAREHOUSE: 'COMPUTE_WH'
          ADDED_FILES: ${{ env.sql_files }}
        run: |
          python .github/workflows/script/dml_changes_script.py  
