name: RBAC_PIPELINE

on:
  workflow_dispatch: # Manual trigger

jobs:
  db_roles_automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set executable permissions for the script
        run: chmod +x .github/workflows/script/fetch_changed_files_script.sh
      - name: Find latest changed json file in RBAC_CHANGES
        id: get_json_file
        run: |
          folder="db_role_grants_config_files"
          file_extension=".json"
          log_count=1

          filtered_files=$(.github/workflows/script/fetch_changed_files_script.sh "$folder" "$file_extension" "$log_count")
          if [ -z "$filtered_files" ]; then
            echo "No json file changes detected in RBAC_CHANGES."
            echo "json_files=[]" >> $GITHUB_ENV
          else
            json_files=$(echo "$filtered_files" | jq -R -s -c 'split("\n")[:-1]')
            echo "json file found: $json_files"
            echo "json_files=$json_files" >> $GITHUB_ENV
          fi
      - name: Install python packages
        if: ${{ env.json_files != '[]' }}
        run: |
          pip install snowflake-connector-python
      - name: Run Python Script
        if: ${{ env.json_files != '[]' }}
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          ADDED_FILES: ${{ env.json_files }}
        run: |
          python rbac_scripts/db_role_automation.py
