name: Trigger Latest PR and Process JSON

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get the latest PR
    - name: Get latest PR
      id: latest_pr
      run: |
        PR=$(gh pr list --state open --sort created --json number --jq '.[0].number')
        echo "Latest PR: $PR"
        echo "pr_number=$PR" >> $GITHUB_ENV

    # Get the latest changed JSON file in the specified folder
    - name: Get latest changed JSON file in db_roles_permissions_config folder
      id: get_json_file
      run: |
        FILE=$(gh pr diff ${{ env.pr_number }} --name-only | grep -E '^repo/rbac/db_roles_permissions_config/.*\.json$' | tail -n 1)
        echo "JSON File: $FILE"
        if [ -z "$FILE" ]; then
          echo "No JSON file changes detected in db_roles_permissions_config folder."
          exit 1
        fi
        echo "json_file=$FILE" >> $GITHUB_ENV
