name: Trigger Latest PR and Process JSON

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with full history to detect file changes
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history to ensure proper diff detection

      # Find the latest changed JSON file in the db_roles_permissions_config folder
      - name: Find latest changed JSON file in db_roles_permissions_config folder
        id: get_json_file
        run: |
          latest_commit=$(git log -1 --pretty=format:%H)
          changed_files=$(git diff-tree --no-commit-id --name-only -r $latest_commit)

          # Filter JSON files in the specified folder
          filtered_files=$(echo "$changed_files" | grep "repo/rbac/db_roles_permissions_config" | grep ".json")

          if [ -z "$filtered_files" ]; then
            echo "No JSON file changes detected in db_roles_permissions_config folder."
            exit 1
          fi

          echo "JSON file found: $filtered_files"
          echo "json_file=$filtered_files" >> $GITHUB_ENV