name: RBAC_PIPELINE

on:
  workflow_dispatch: # Manual trigger

jobs:
  db_roles_automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find latest changed json file in RBAC_CHANGES
        id: get_json_file
        run: |
          latest_commits=$(git log origin/main --merges --grep="Merge pull request" -1 --pretty=format:%H)

          # Initialize an empty array to store files
          declare -A file_set

          # Loop through the commits to collect changed files
          for commit in $latest_commits; do
              commit_files=$(git diff-tree --no-commit-id --name-status -r $commit | awk '$1 != "D" {print $NF}')
              for file in $commit_files; do
                  file_set["$file"]=1  # Store files in associative array for uniqueness
              done
          done

          # Extract unique files from the array
          changed_files=$(printf "%s\n" "${!file_set[@]}")
          echo $ changed_files
          # Filter json files in the specified folder
          filtered_files=$(echo "$changed_files" | grep "db_role_grants_config_files" | grep ".json" || true)
          if [ -z "$filtered_files" ]; then
            echo "No json file changes detected in RBAC_CHANGES."
            echo "json_files=[]" >> $GITHUB_ENV
          else
            json_files=$(echo "$filtered_files" | jq -R -s -c 'split("\n")[:-1]')
            echo "json file found: $json_files"
            echo "json_files=$json_files" >> $GITHUB_ENV
          fi
      - name: Install python packages
        if: ${{ env.json_files != '[]' }}
        run: |
          pip install snowflake-connector-python
      - name: Run Python Script
        if: ${{ env.json_files != '[]' }}
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          ADDED_FILES: ${{ env.json_files }}
        run: |
          python rbac_scripts/db_role_automation.py
