name: Trigger Latest PR and Process JSON

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  process-json:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code with full history to detect file changes
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history to ensure proper diff detection

    # Get the latest PR number from the GitHub context (if running on a PR)
    - name: Get PR number
      id: pr_info
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        else
          echo "This workflow wasn't triggered by a PR."
        fi

    # Find the latest changed JSON file in db_roles_permissions_config folder
    - name: Find latest changed JSON file in db_roles_permissions_config folder
      id: get_json_file
      run: |
        latest_merged_pr=$(git log --merges --oneline | head -1 | cut -f1)
        changed_files=$(git diff --name-only $latest_merged_pr main)
        filtered_files=$(echo "$changed_files" | grep "repo/rbac/rbac_permissions_config")
        if [ -z "$filtered_files" ]; then
          echo "No JSON file changes detected in db_roles_permissions_config folder."
          exit 1
        fi
        echo "$filtered_files"
        echo "json_file=$filtered_files" >> $GITHUB_ENV
        